### ISSUE TITLE
Support Distillery packaging

### ISSUE THREAD

**Issue by davejlong** [kittoframework/kitto#100]
Ticket to track issues with packaging releases with [Distillery](https://github.com/bitwalker/distillery)

## Todo:

[] [Remove use of `Mix` module](https://github.com/kittoframework/kitto/issues/100#issuecomment-287876950)

**Comment by davejlong** [comment]
It appears that the Distillery does not include the `Mix` module set in releases, so we need to replace any references to `Mix` in Kitto with some other form of determining release stages.

```
> ag --ignore lib/mix "Mix" lib
lib/kitto/code_reloader.ex
32:    Application.get_env(:kitto, :reload_code?, true) && Mix.env == :dev
66:        file |> lib? -> Mix.Tasks.Compile.Elixir.run ["--ignore-module-conflict"]

lib/kitto/router.ex
7:  unless Mix.env == :test, do: plug Plug.Logger
92:    if Mix.env == :dev do

lib/kitto.ex
24:    Supervisor.start_link(children(Mix.env), opts)
```

**Comment by zorbash** [comment]
Almost everything's in place for distillery in 0.6.0-rc0 release.
To try it follow the instructions below:

### Instructions

1. Install 0.6.0-rc0 installer `mix archive.install https://github.com/kittoframework/archives/raw/master/kitto_new-0.6.0-rc0.ez`
1. Generate a new dashboard application `mix kitto.new something`
1. `cd something`
1. Change `mix.exs` to point to kitto at version `0.6.0-rc0`
1. Add distillery 1.3.1 as a dependency in your mix.exs and `mix deps.get`
1. Change config/prod.exs to have `config :kitto, root: :otp_app
1. Run `MIX_ENV=prod mix release --env=prod` to create the release

**Comment by drumusician** [comment]
Ok, after following the exact steps above and hitting the root page, it crashes:

Here is the stacktrace:

```
Server: localhost:4000 (http)
Request: GET /dashboards/sample
** (exit) an exception was raised:
    ** (File.Error) could not read file "./dashboards/error.html.eex": no such file or directory
        (elixir) lib/file.ex:244: File.read!/1
        (eex) lib/eex.ex:181: EEx.compile_file/2
        (eex) lib/eex.ex:216: EEx.eval_file/3
        (kitto) lib/kitto/router.ex:112: Kitto.Router.render_error/3
        (plug) lib/plug/error_handler.ex:94: Plug.ErrorHandler.__catch__/6
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Is there a step missing? Let me know what else you need for debugging.

**Comment by zorbash** [comment]
@drumusician Can you paste the contents of your:

* config/config.exs
* config/production.exs
* rel/config.exs
* mix.exs

And the output of `ls -l _build/prod/rel/distil4/lib/<name-of-your-dashboard>-0.0.1`

Finally, how did you start the server?
With `_build/prod/rel/distil4/bin/your-dashboard-name foreground` ?

**Comment by drumusician** [comment]
@Zorbash Sorry, my bad... ;(

I forgot to save the config/prod.exs file before trying... so all good. I'll try on my own project as well :)

**Comment by zorbash** [comment]
Thank you for your effort @drumusician . I'll amend the [upgrading-guide](https://github.com/kittoframework/kitto/wiki/Upgrading-Guide) with upgrading instructions for dashboards generated with a <0.6.0 installer.
