### ISSUE TITLE
Clickable Links in Widgets?

### ISSUE THREAD

**Issue by alexcurtin** [kittoframework/kitto#111]
How would I make a clickable link inside say the List widget? That way a user could interact with a widget square?

**Comment by davejlong** [comment]
@alexcurtin this is an issue with Gridster. See [this thread](https://github.com/Shopify/dashing/issues/431) on Dashing's repo for more information on a workaround.

**Comment by davejlong** [comment]
Furthermore, with Gridster appearing to be a dead project (https://github.com/dustmoo/gridster.js/issues/51) we should investigate switching to something like [gridstack.js](http://troolee.github.io/gridstack.js/)
