### ISSUE TITLE
Change Color of Widget based on Data

### ISSUE THREAD

**Issue by alexcurtin** [kittoframework/kitto#114]
How would I go about changing the color of 1 single widget depending on data sent to that widget, since they share css classes?

**Comment by zorbash** [comment]
@alexcurtin did you get an answer for this?

**Comment by davejlong** [comment]
Don't know how I closed this. Anyways, the class of a widget can be overriden from the JS widget. An example of this can be found in the [Text widget](https://github.com/kittoframework/kitto/blob/master/installer/templates/new/widgets/text/text.js). The value of `status` from the data source will be used as an additional class applied to the widget.

So passing data to the Text widget like `{text: "Something awesome happened!", status: "success"}` will set `success` as an additional class on the widget and in your CSS you can add something like:

```
.widget-text.success {
   background-color: green;
}
```
