### ISSUE TITLE
Can this be used in an existing project? 

### ISSUE THREAD

**Issue by isAlmogK** [kittoframework/kitto#125]
Can you use this inside an existing project as a dashboard view/page?

**Comment by zorbash** [comment]
@AlmogRnD You can have it as an app under an umbrella application (see: https://github.com/kittoframework/kitto/wiki/Umbrella-Apps).

If you need further help on how this can work, let's chat on gitter (https://gitter.im/kittoframework/Lobby).

I'll close this issue as I prefer to keep issues mostly about bug reports. Thanks.
