### ISSUE TITLE
No matching version for kitto ~> 0.9.1 (from: mix.exs) in registry

### ISSUE THREAD

**Issue by juvirez** [kittoframework/kitto#130]
### Environment

* Kitto version: 0.9.1
* Elixir / Hex version (mix hex.info): 1.8.1 / 0.19.0
* Node / NPM version (node -v) (npm -v): 11.6.0 / 6.5.0
* Operating system: macOS 10.14.2

### Current behavior
Follow instructions from Readme:
```
$ mix archive.install https://github.com/kittoframework/archives/raw/master/kitto_new-0.9.1.ez
$ mix kitto.new dashboard
$ cd dashboard
$ mix deps.get
** (Mix) No matching version for kitto ~> 0.9.1 (from: mix.exs) in registry

The latest version is: 0.9.0
```

### Expected behavior
Install instructions from Readme should be correct.

**Comment by zorbash** [comment]
@juvirez version 0.9.1 has been pushed, so there's no need to update the README. Thanks for pointing this out.
