### ISSUE TITLE
Authentication/Authorization supported?

### ISSUE THREAD

**Issue by kidneybeanred** [kittoframework/kitto#133]
I didn't see anything regarding this listed so I thought I'd ask, is there a way to restrict users from certain dashboards? What are people doing to implement this? 

Heres's smashing's HOWTO https://github.com/Smashing/smashing/wiki/How-to%3A-Add-authentication

**Comment by zorbash** [comment]
At the moment such a feature has not been implemented. I'd be glad to see a PR for HTTP basic Auth or IP check merged.

**Comment by kidneybeanred** [comment]
Thanks @zorbash. Just quickly, what are users using now without this? Rolling out their own setup using ueber auth? Any ideas? Thanks again

**Comment by zorbash** [comment]
Ideally you'll deploy Kitto behind a reverse proxy like Nginx, for which there are plenty of guides on how to setup HTTP Basic Auth.
