### ISSUE TITLE
Remote reloading dashboards

### ISSUE THREAD

**Issue by davejlong** [kittoframework/kitto#14]
Dashboards may often times be running on things like TVs which aren't easy to manually reload after updating. It'd be nice to have a URL like in Dashing that upon requesting would reload specific dashboards or all dashboards open.

**Comment by davejlong** [comment]
In Dashing's implementation of the API, you would build a request like the following to reload a single dashboard across all clients:

```
curl -i -d '{ "auth_token": "YOUR_AUTH_TOKEN", "event": "reload"}' http://localhost:3030/dashboards/sample
```

Or to reload all dashboards across all clients:

```
curl -i -d '{ "auth_token": "YOUR_AUTH_TOKEN", "event": "reload"}' http://localhost:3030/dashboards/*
```

**Comment by zorbash** [comment]
It's a feature worth porting from Dashing. Will you implement it?

**Comment by davejlong** [comment]
Yeah, I'll take it. I am very new to React, so I might need some help on the front end, but I'll take assignment for now.

**Comment by zorbash** [comment]
We can reserve a broadcasting topic with a name eg `:kitto` or `:_kitto_` to be used for internal commands to the frontend. 

Then we can change https://github.com/kittoframework/kitto/blob/master/installer/templates/new/assets/javascripts/widget.js#L17

with one more event listener for internal events and add mappings to commands like `restart`.
