### ISSUE TITLE
Intermittent test failure in stats_server_test

### ISSUE THREAD

**Issue by davejlong** [kittoframework/kitto#16]
Intermittently, I get errors when running the test suite:

```
  1) test #measure when a job fails does not increment :total_running_time (Kitto.StatsServerTest)
     test/stats_server_test.exs:73
     Assertion with == failed
     code: Kitto.StatsServer.stats().dummy_job().total_running_time()== running_time
     lhs:  2.0e-6
     rhs:  1.0e-6
     stacktrace:
       test/stats_server_test.exs:82: (test)
```

The lhs and rhs change, but they are always off by a tiny amount.

**Comment by davejlong** [comment]
As an additional note, the test seed doesn't seem to effect it. I can run with the same seed 5 times and the tests will generally fail 1 of those times.

**Comment by zorbash** [comment]
This test has to be refactored, it sometimes breaks in travis too :-/
