### ISSUE TITLE
Define `broadcast/1` inside a job declaration

### ISSUE THREAD

**Issue by zorbash** [kittoframework/kitto#22]
It seems quite intuitive to have a job definition like the following:

```elixir
use Kitto.Job.DSL

job :jenkins, every: :minute do
  broadcast! Jenkins.some_api_request
end
```

Where `broadcast!` will use the name of the job as the topic.

**Comment by davejlong** [comment]
I like it. I'd assume 90% of jobs only broadcast a single metric (except when it's me writing JIRA jobs  😜). What would happen if someone tried to broadcast twice within a job?

**Comment by zorbash** [comment]
> What would happen if someone tried to broadcast twice within a job?

Do you mean something like:

``` elixir
use Kitto.Job.DSL

job :jenkins, every: :minute do
  broadcast! Jenkins.some_api_request
  broadcast! Jenkins.some_other_api_request
end
```

?

`broadcast!` would emit two events to the same topic.

**Comment by zorbash** [comment]
Implemented in https://github.com/kittoframework/kitto/commit/e035f4c03974d4daf4e4851506659fdb384df30b
