### ISSUE TITLE
Improve job restart functionality

### ISSUE THREAD

**Issue by davejlong** [kittoframework/kitto#23]
Right now when a job fails it will restart immediately. This can become problematic when working with APIs and such where that restart may cause some serious issues for the downstream layers. The default value set in `lib/kitto/runner.ex` is 300 restarts, which means that a job is allowed to restart 300 times in 5 seconds.

There's more discussion to be had on this, but it might be a good idea to have some sort of graceful backoff algorithm so not put too much pressure on downstream services.

**Comment by zorbash** [comment]
The `300` restarts is an arbitrary value which seems to serve the demo app well at the moment, but needs to evolve to a more sophisticated policy.

I was planning to introduce a configurable backoff setting for jobs. https://github.com/kittoframework/kitto/blob/master/lib/kitto/stats_server.ex was originally implemented to pave the way towards such a feature. I was also considering using https://github.com/ferd/backoff (or the Elixir port https://github.com/mingchuno/exbackoff)
