### ISSUE TITLE
Find a logo

### ISSUE THREAD

**Issue by zorbash** [kittoframework/kitto#31]
It would be nice to have a logo for this project.

**Comment by jhstatewide** [comment]
![kitto-logo](https://cloud.githubusercontent.com/assets/49839/20605515/c401b1be-b239-11e6-83b8-846446882e73.png)

**Comment by JanStevens** [comment]
This might help: http://logojoy.com/app.php

**Comment by zorbash** [comment]
@jhstatewide thanks a lot for contributing a design. I'll keep this issue until we have a few more options to evaluate and make a choice.

**Comment by srekoble** [comment]
Some suggestions for kitto logo, feel free to provide feedback.

![group 4](https://cloud.githubusercontent.com/assets/2699186/21293028/0fd63e44-c521-11e6-8d10-911cad7ac39b.png)

![group 3](https://cloud.githubusercontent.com/assets/2699186/21293027/0fcdd574-c521-11e6-8fc4-92bf6b8d57b1.png)

**Comment by JanStevens** [comment]
The last one is very pretty! Nice job

**Comment by davejlong** [comment]
@srekoble Can you split the logos up into 2 comments: 1 for the sketch style and the other for the cursive style? That way voting can naturally happen by people adding emoji reactions to the different logos.

**Comment by zorbash** [comment]
@davejlong fixed

@srekoble 's logo `#1`


![](https://cloud.githubusercontent.com/assets/2699186/21293028/0fd63e44-c521-11e6-8d10-911cad7ac39b.png)

**Comment by zorbash** [comment]
@srekoble  's logo `#2` 

![](https://cloud.githubusercontent.com/assets/2699186/21293027/0fcdd574-c521-11e6-8fc4-92bf6b8d57b1.png)

**Comment by zorbash** [comment]
I really like the last one, it has a playful essence :candy:. Other collaborators have also expressed the same preference, so I'm closing this issue.

**Comment by zorbash** [comment]
@srekoble Thanks a lot for you contribution! :tada:
