### ISSUE TITLE
Support for streaming jobs

### ISSUE THREAD

**Issue by davejlong** [kittoframework/kitto#32]
Jobs should be able to be written in a manner to start and keep running for all time, restarting if the job fails. This would support the ability to write jobs that stream data from APIs like Twitter which support streaming.

The job definition would look something like:

```elixir
job :twitter, type: :streaming do
  ExTwitter.stream_filter(track: "apple")
  |> Stream.map(fn(x) -> broadcast!(:tweet, x) end)
end
```

Adding the `type` attribute to the options map for jobs, would mean that the default `type` would be something like `scheduled` for traditional jobs that poll for data.

**Comment by zorbash** [comment]
Currently defining a job without an interval implicitly creates a streaming job.
See: https://github.com/kittoframework/kitto/blob/master/lib/kitto/job/dsl.ex#L33

I think we need to provide a working example in the wiki for this feature.

**Comment by zorbash** [comment]
Added example in the wiki for streaming jobs. https://github.com/kittoframework/kitto/wiki/Streaming-Jobs
