### ISSUE TITLE
Add tests for installer

### ISSUE THREAD

**Issue by zorbash** [kittoframework/kitto#35]
We have to make sure the installer generates all necessary files.

**Comment by JanStevens** [comment]
I can take that one up

**Comment by zorbash** [comment]
@JanStevens great!, go ahead.

**Comment by zorbash** [comment]
@JanStevens are you still interested in this?

**Comment by JanStevens** [comment]
Right forgot about it, will take a look tomorrow evening

**Comment by zorbash** [comment]
Added in https://github.com/kittoframework/kitto/commit/46d3f1744e1e42cd7ac1f734ed5119868f3e75bd
