### ISSUE TITLE
Support Job Reloading - Speed Up Compile Cycle

### ISSUE THREAD

**Issue by jhstatewide** [kittoframework/kitto#37]
Played around with Kitto a bit -- on my system WebPack takes a minute or two to do the build. It would be nicer if either:

1) WebPack could cache builds(?) or somehow be sped up
2) All classes, jobs, etc can hot reload to speed up testing

If I need to restart the server every time I have a tweak I'll be waiting for WebPack to build quite a bit.

**Comment by zorbash** [comment]
@jhstatewide thanks for the suggestions.

About:

> WebPack takes a minute or two to do the build

What are the specs of your system? Do you mean the production build (`npm run build`) or the intermediate builds by `webpack-dev-server` (which is started with mix kitto.server?

2) All classes, jobs, etc can hot reload to speed up testing

Job reloading on development is a nice idea and i think we can support it with minimal changes.

In the meantime, you can start the Kitto backend with `iex -S mix` in one terminal tab and 
`npm run start` in another.

**Comment by jhstatewide** [comment]
I mean the intermediate builds on webpack-dev-server. When I was working on my test project I was starting kitto.server and killing it when I had a change in either my jobs or other supporting code.

Good tip on iex -S mix and npm run start in separate terminals. I'll do that from now on. 
I am more used to the phoenix workflow -- start mix phoenix.server and go from there (it will hot reload most code).
