### ISSUE TITLE
Generate error pages

### ISSUE THREAD

**Issue by zorbash** [kittoframework/kitto#41]
Let's display error pages for 404, 500 http error codes.

**Comment by davejlong** [comment]
There are 2 changes to the router to have pretty 404 and 500 templates.

## Creating the 404 page

* Create an EEx template somewhere in `installer/templates/new` with the 404 page
* Ensure the template gets copied in by adding to the `@new` list in `installer/lib/kitto_new.ex`
* Change the `map _ do` in `lib/kitto/router.ex` to render your 404 template

## Creating the 500 page

* Create an EEx template somewhere in `installer/templates/new` with the 500 page
* Ensure the template gets copied in by adding to the `@new` list in `installer/lib/kitto_new.ex`
* In `lib/kitto/router.ex`:
  * Include the `Plug.ErrorHandler` at the top of the router
  * Add a `handle_errors/2` method which renders the 500 template

More details on using `Plug.ErrorHandler` can be found in the [`Plug` docs](https://hexdocs.pm/plug/1.3.0/Plug.ErrorHandler.html)

**Comment by davejlong** [comment]
If someone who's new to Elixir wants to pair on this to get a PR in for 24PullRequests.org, I'm happy to help.

**Comment by zorbash** [comment]
Implemented in #51.
