### ISSUE TITLE
How to connect Server PORT in kitto

### ISSUE THREAD

**Issue by ThetNaungSoe** [kittoframework/kitto#74]
How to connect Server PORT in kitto

**Comment by zorbash** [comment]
Read the Heroku deployment guide:

https://github.com/kittoframework/kitto/wiki/Deploying-to-Heroku#configure-binding-address

Same applies to issue #70.

Please prefer to use the [Gitter chat](https://gitter.im/kittoframework/Lobby) for questions and discussion of this kind.
The issue tracker is primarily intended for bugs and suggestions.
