### ISSUE TITLE
Upgrade plug

### ISSUE THREAD

**Issue by davejlong** [kittoframework/kitto#92]
Based on a recent vulnerability discovered in Plug, we should hardcode the version of plug used to be 1.3.2 or greater. Full details of the vulnerability are at https://groups.google.com/d/msg/elixir-lang-core/cL9OLMT1DHQ/gWQt_d5_DAAJ

**Comment by zorbash** [comment]
Even though we're not directly affected, we should do it. Will you open a PR?
